#!/usr/bin/env python3
"""
cross-install.py — Dopagent 跨平台安装器

用法:
  python cross-install.py claude-code    # Claude Code
  python cross-install.py cursor         # Cursor
  python cross-install.py copilot        # GitHub Copilot
  python cross-install.py codex          # Codex CLI
  python cross-install.py windsurf       # Windsurf
  python cross-install.py openclaw       # OpenClaw
  python cross-install.py all            # 安装到所有检测到的平台
  python cross-install.py list           # 列出支持平台

平台差异:
  Claude Code  → .claude/skills/dopagent/ + CLAUDE.md
  Cursor       → .cursor/skills/dopagent/ + .cursorrules
  Copilot      → .github/copilot-instructions.md
  Codex        → .codex/skills/dopagent/ + AGENTS.md
  Windsurf     → .windsurf/rules/dopagent.md
  OpenClaw     → skills/dopagent/ + MEMORY.md
"""

import sys
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.resolve()
HOME = Path.home()

# ── 平台定义 ──
PLATFORMS = {
    "claude-code": {
        "name": "Claude Code",
        "skill_dir": HOME / ".claude" / "skills" / "dopagent",
        "context_file": ".claude" / "CLAUDE.md",
        "context_label": "CLAUDE.md (project root)",
        "strip_yaml": True,
        "context_inject": "# Dopagent instincts — auto-generated by cross-install.py\nHindsight recall → python $WORKSPACE/alaya_recall.py\nOn correction → fill template → retain to Hindsight (imp:8)\nOn push → confirm with User first, no personal pronouns in commit messages.\n",
    },
    "cursor": {
        "name": "Cursor",
        "skill_dir": HOME / ".cursor" / "skills" / "dopagent",
        "context_file": ".cursorrules",
        "context_label": ".cursorrules (project root)",
        "strip_yaml": True,
        "context_inject": "# Dopagent instincts\nHindsight recall → python $WORKSPACE/alaya_recall.py\nOn correction → fill template → retain to Hindsight (imp:8)\nOn push → confirm with User first, no personal pronouns in commit messages.\n",
    },
    "copilot": {
        "name": "GitHub Copilot",
        "skill_dir": None,
        "context_file": ".github" / "copilot-instructions.md",
        "context_label": ".github/copilot-instructions.md (project root)",
        "strip_yaml": True,
        "context_inject": "# Dopagent instincts\nHindsight recall → python $WORKSPACE/alaya_recall.py\nOn correction → fill template → retain to Hindsight (imp:8)\nOn push → confirm with User first, no personal pronouns in commit messages.\n",
    },
    "codex": {
        "name": "Codex CLI",
        "skill_dir": HOME / ".codex" / "skills" / "dopagent",
        "context_file": "AGENTS.md",
        "context_label": "AGENTS.md (project root)",
        "strip_yaml": True,
        "context_inject": "# Dopagent instincts\nHindsight recall → python $WORKSPACE/alaya_recall.py\nOn correction → fill template → retain to Hindsight (imp:8)\nOn push → confirm with User first, no personal pronouns in commit messages.\n",
    },
    "windsurf": {
        "name": "Windsurf",
        "skill_dir": None,
        "context_file": ".windsurf" / "rules" / "dopagent.md",
        "context_label": ".windsurf/rules/dopagent.md",
        "strip_yaml": False,
        "context_inject": None,
    },
    "openclaw": {
        "name": "OpenClaw",
        "skill_dir": HOME / "skills" / "dopagent",
        "context_file": "MEMORY.md",
        "context_label": "MEMORY.md (project root)",
        "strip_yaml": False,
        "context_inject": "# Dopagent instincts\nHindsight recall → python $WORKSPACE/alaya_recall.py\nOn correction → fill template → retain to Hindsight (imp:8)\nOn push → confirm with User first, no personal pronouns in commit messages.\n",
    },
}


def list_platforms():
    print("Supported platforms:")
    for key, p in PLATFORMS.items():
        print(f"  {key:15s} → {p['skill_dir'] or p['context_file']}")


def install(target: str):
    if target not in PLATFORMS:
        print(f"Unknown platform: {target}")
        print(f"Available: {', '.join(PLATFORMS.keys())}")
        sys.exit(1)

    p = PLATFORMS[target]
    print(f"Installing for {p['name']}...\n")

    src = PROJECT_ROOT / "SKILL.md"
    content = src.read_text(encoding="utf-8")

    # 1. Copy skill
    if p["skill_dir"]:
        p["skill_dir"].mkdir(parents=True, exist_ok=True)
        if p["strip_yaml"]:
            # Strip YAML frontmatter for platforms that use bare markdown
            lines = content.split("\n")
            if lines[0].strip() == "---":
                end = lines.index("---", 1) if "---" in lines[1:] else 0
                body = "\n".join(lines[end+1:]) if end else content
            else:
                body = content
            (p["skill_dir"] / "SKILL.md").write_text(body, encoding="utf-8")
        else:
            (p["skill_dir"] / "SKILL.md").write_text(content, encoding="utf-8")
        print(f"  ✅ SKILL.md → {p['skill_dir']}")

    # 2. Inject instincts
    if p["context_inject"] and p["context_file"]:
        ctx_file = Path(p["context_file"])
        existing = ctx_file.read_text(encoding="utf-8") if ctx_file.exists() else ""
        if "Dopagent instincts" not in existing:
            ctx_file.parent.mkdir(parents=True, exist_ok=True)
            ctx_file.write_text(existing + "\n" + p["context_inject"], encoding="utf-8")
            print(f"  ✅ Instincts injected → {p['context_label']}")
        else:
            print(f"  ⏭  Instincts already present in {p['context_label']}")

    # 3. Run core install
    import subprocess
    result = subprocess.run(
        [sys.executable, str(PROJECT_ROOT / "install.py")],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print(f"  ✅ install.py completed")
    else:
        print(f"  ⚠️  install.py had issues:\n{result.stderr[:300]}")

    print(f"\nDone. {p['name']} is set up with Dopagent.")


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] in ("list", "--list"):
        list_platforms()
    elif sys.argv[1] in PLATFORMS:
        install(sys.argv[1])
    else:
        print(f"Usage: python cross-install.py <platform>")
        list_platforms()
